// ============================================================
// PARDA FAAS — Character Configuration
// All 7 playable investigators with stats, abilities, archetypes
// ============================================================

export const ARCHETYPES = {
  FAST_AGGRESSIVE: {
    id: 'fast_aggressive',
    label: '⚡ Fast & Aggressive',
    labelNP: '⚡ तीव्र र आक्रामक',
    color: '#FF6B00',
    badge: 'fast-badge',
    description: 'High speed, high risk — explosive evidence gathering.',
  },
  METHODICAL: {
    id: 'methodical',
    label: '🔬 Methodical & Thorough',
    labelNP: '🔬 सुव्यवस्थित र गहन',
    color: '#0D7377',
    badge: 'method-badge',
    description: 'Slower but immune to anchoring traps. High credibility ceiling.',
  },
  NETWORKER: {
    id: 'networker',
    label: '🤝 Networker',
    labelNP: '🤝 सञ्जालकर्ता',
    color: '#F1C40F',
    badge: 'network-badge',
    description: 'Witness cooperation bonuses, squad buffs, community intelligence.',
  },
};

export const CHARACTERS = {
  balen: {
    id: 'balen',
    name: 'Balen',
    nameNP: 'बालेन',
    title: 'Urban Warrior',
    titleNP: 'शहरी योद्धा',
    archetype: 'FAST_AGGRESSIVE',
    color: '#FF6B00',
    // Stats 0–100
    stats: {
      speed: 90,
      stealth: 30,
      intel: 60,
      credibility: 70,
      defense: 55,
      accuracy: 65,
    },
    special: {
      key: 'Q',
      name: 'Demo Mode',
      nameNP: 'डेमो मोड',
      description: 'Smashes one corruption bubble layer instantly.',
      descriptionNP: 'एउटा भ्रष्टाचार बुलबुला तह तुरुन्त फोड्छ।',
      cooldown: 15000, // ms
      duration: 0,
      icon: '💥',
    },
    personality: 'Aggressive, direct, fiery',
    personalityNP: 'आक्रामक, प्रत्यक्ष, जोशिलो',
    quote: '"म काम गर्छु, बोल्दिन।"',
    quoteEN: '"I work, I don\'t just talk."',
    unlocked: true, // free tier
    color2: '#C0392B',
  },

  sudan_gurung: {
    id: 'sudan_gurung',
    name: 'Sudan Gurung',
    nameNP: 'सुदान गुरुङ',
    title: 'Field Investigator',
    titleNP: 'फिल्ड अन्वेषक',
    archetype: 'NETWORKER',
    color: '#F1C40F',
    stats: {
      speed: 65,
      stealth: 70,
      intel: 90,
      credibility: 75,
      defense: 60,
      accuracy: 70,
    },
    special: {
      key: 'Q',
      name: 'Network Tap',
      nameNP: 'नेटवर्क ट्याप',
      description: 'Reveals all hidden witnesses for 10 seconds.',
      descriptionNP: 'सबै लुकेका साक्षीहरूलाई १० सेकेन्डका लागि देखाउँछ।',
      cooldown: 20000,
      duration: 10000,
      icon: '📡',
    },
    personality: 'Tactical, networked',
    personalityNP: 'रणनीतिक, सञ्जालयुक्त',
    quote: '"जानकारी नै शक्ति हो।"',
    quoteEN: '"Information is power."',
    unlocked: false,
    color2: '#B7950B',
  },

  aasika_tamang: {
    id: 'aasika_tamang',
    name: 'Aasika Tamang',
    nameNP: 'आसिका तामाङ',
    title: 'Youth Activist',
    titleNP: 'युवा कार्यकर्ता',
    archetype: 'FAST_AGGRESSIVE',
    color: '#E91E8C',
    stats: {
      speed: 80,
      stealth: 50,
      intel: 65,
      credibility: 90,
      defense: 40,
      accuracy: 60,
    },
    special: {
      key: 'Q',
      name: 'Viral Post',
      nameNP: 'भाइरल पोस्ट',
      description: 'Multiplies evidence value ×2 for 8 seconds.',
      descriptionNP: '८ सेकेन्डका लागि प्रमाणको मूल्य दोब्बर गर्छ।',
      cooldown: 18000,
      duration: 8000,
      icon: '📱',
    },
    personality: 'Energetic, bold',
    personalityNP: 'ऊर्जावान, साहसी',
    quote: '"युवाको आवाज सुन्नैपर्छ।"',
    quoteEN: '"The youth\'s voice must be heard."',
    unlocked: true, // free tier
    color2: '#C2185B',
  },

  nikolas_bhushal: {
    id: 'nikolas_bhushal',
    name: 'Nikolas Bhushal',
    nameNP: 'निकोलस भुसाल',
    title: 'Tech Analyst',
    titleNP: 'प्रविधि विश्लेषक',
    archetype: 'METHODICAL',
    color: '#0D7377',
    stats: {
      speed: 50,
      stealth: 65,
      intel: 95,
      credibility: 80,
      defense: 70,
      accuracy: 95,
    },
    special: {
      key: 'Q',
      name: 'Data Decrypt',
      nameNP: 'डाटा डिक्रिप्ट',
      description: 'Auto-solves one document puzzle instantly.',
      descriptionNP: 'एउटा कागजात पजल तुरुन्त स्वतः सुल्झाउँछ।',
      cooldown: 25000,
      duration: 0,
      icon: '💻',
    },
    personality: 'Methodical, sharp',
    personalityNP: 'सुव्यवस्थित, तीक्ष्ण',
    quote: '"तथ्यांकले झूठ बोल्दैन।"',
    quoteEN: '"Data never lies."',
    unlocked: false,
    color2: '#08494C',
  },

  punya_gautam: {
    id: 'punya_gautam',
    name: 'Punya Gautam',
    nameNP: 'पुण्य गौतम',
    title: 'Journalist',
    titleNP: 'पत्रकार',
    archetype: 'FAST_AGGRESSIVE',
    color: '#C0392B',
    stats: {
      speed: 95,
      stealth: 45,
      intel: 70,
      credibility: 75,
      defense: 35,
      accuracy: 80,
    },
    special: {
      key: 'Q',
      name: 'Breaking Story',
      nameNP: 'ब्रेकिङ स्टोरी',
      description: 'Freezes official countermoves for 12 seconds.',
      descriptionNP: 'अधिकारीका काउन्टरमुभहरू १२ सेकेन्डका लागि रोक्छ।',
      cooldown: 22000,
      duration: 12000,
      icon: '📰',
    },
    personality: 'Fast, sharp-tongued',
    personalityNP: 'तीव्र, तीखो भाषी',
    quote: '"सत्य बाहिर आउँछ नै।"',
    quoteEN: '"Truth always comes out."',
    unlocked: false,
    color2: '#922B21',
  },

  rishi_dhamala: {
    id: 'rishi_dhamala',
    name: 'Rishi Dhamala',
    nameNP: 'ऋषि धमला',
    title: 'TV Anchor',
    titleNP: 'टिभी एंकर',
    archetype: 'NETWORKER',
    color: '#8E44AD',
    stats: {
      speed: 60,
      stealth: 40,
      intel: 75,
      credibility: 85,
      defense: 55,
      accuracy: 70,
    },
    special: {
      key: 'Q',
      name: 'Live Broadcast',
      nameNP: 'लाइभ ब्रोडकास्ट',
      description: 'Reveals the correct evidence trail for 6 seconds.',
      descriptionNP: 'सही प्रमाण मार्ग ६ सेकेन्डका लागि देखाउँछ।',
      cooldown: 20000,
      duration: 6000,
      icon: '📺',
    },
    personality: 'Dramatic, charismatic',
    personalityNP: 'नाटकीय, करिश्माई',
    quote: '"बताउनुहोस् — सत्य के हो?"',
    quoteEN: '"Tell me — what is the truth?"',
    unlocked: false,
    color2: '#6C3483',
  },

  mahabir_pun: {
    id: 'mahabir_pun',
    name: 'Mahabir Pun',
    nameNP: 'महावीर पुन',
    title: 'Calm Innovator',
    titleNP: 'शान्त नवप्रवर्तक',
    archetype: 'METHODICAL',
    color: '#27AE60',
    stats: {
      speed: 40,
      stealth: 75,
      intel: 80,
      credibility: 95,
      defense: 90,
      accuracy: 75,
    },
    special: {
      key: 'Q',
      name: 'Mountain Patience',
      nameNP: 'पहाडी धैर्य',
      description: 'Regenerates integrity bar; immune to bribe traps.',
      descriptionNP: 'इन्टिग्रिटी बार पुनर्भर गर्छ; घुस जालबाट प्रतिरक्षित।',
      cooldown: 30000,
      duration: 15000,
      icon: '⛰️',
    },
    personality: 'Wise, unshakeable',
    personalityNP: 'बुद्धिमान, अडिग',
    quote: '"पहाड हल्लिँदैन।"',
    quoteEN: '"The mountain does not shake."',
    unlocked: true, // free tier
    color2: '#1E8449',
  },
};

export const CHARACTER_ORDER = [
  'balen', 'aasika_tamang', 'mahabir_pun',
  'sudan_gurung', 'nikolas_bhushal', 'punya_gautam', 'rishi_dhamala',
];

export const FREE_CHARACTERS = ['balen', 'aasika_tamang', 'mahabir_pun'];
